In [1]:
import azureml.core
from azureml.core.authentication import InteractiveLoginAuthentication
from azureml.core import Experiment, Workspace

# Check core SDK version number
print("You are currently using version", azureml.core.VERSION, "of the Azure ML SDK")
print("")

# Log In to Azure ML Workspace
interactive_auth = InteractiveLoginAuthentication(tenant_id="76f90eb1-fb9a-4446-9875-4d323d6455ad")

ws = Workspace.from_config(auth=interactive_auth)
print('Workspace name: ' + ws.name, sep='\n')

You are currently using version 1.8.0 of the Azure ML SDK

Workspace name: team20


In [31]:
from azureml.core import Dataset

# get the dataset from Azure ML Workspace
aml_dataset = Dataset.get_by_name(ws, 'train_ds', version='latest')
pdf = aml_dataset.take(1000).to_pandas_dataframe()

In [38]:
import sys
sys.path.append('../scripts')
from metrics import custom_metric

In [11]:
import numpy as np
import pandas as pd

In [27]:
pdf['uplift'] = np.random.rand(pdf.shape[0])
custom_metric(pdf)

-0.67362499074691

In [30]:
import modin.pandas as pd

In [32]:
data = aml_dataset.to_pandas_dataframe()

In [41]:
sys.path.append('..')

In [42]:
from scripts.metrics import random_predictions

In [120]:
random_predictions(data, iterations=5)

0.7208413684359444

In [70]:
from scripts.pipeline import StupidModel, run

In [48]:
model = StupidModel()

In [71]:
import scripts

In [121]:
from importlib import reload
reload(scripts.pipeline)
from scripts.pipeline import StupidModel, run

In [79]:
data['gender'].replace({'Ж': 0, 'М': 1, 'Не определен': np.NaN}, inplace=True)

In [96]:
kf = KFold(n_splits=4)
for a in kf.split(data):
    print(a)

(array([171758, 171759, 171760, ..., 687026, 687027, 687028]), array([     0,      1,      2, ..., 171755, 171756, 171757]))
(array([     0,      1,      2, ..., 687026, 687027, 687028]), array([171758, 171759, 171760, ..., 343512, 343513, 343514]))
(array([     0,      1,      2, ..., 687026, 687027, 687028]), array([343515, 343516, 343517, ..., 515269, 515270, 515271]))
(array([     0,      1,      2, ..., 515269, 515270, 515271]), array([515272, 515273, 515274, ..., 687026, 687027, 687028]))


In [123]:
data.sample(1000)

CardHolder   age  cheque_count_12m_g20  cheque_count_12m_g21  \
537412    15729839  39.0                   0.0                   0.0   
607270    15679613  44.0                   2.0                   1.0   
406983    16088120  69.0                   0.0                  25.0   
369791    16490644  27.0                   2.0                   4.0   
326614    16180572  63.0                   0.0                   0.0   
...            ...   ...                   ...                   ...   
669733    15710786  40.0                   1.0                   0.0   
171542    16498213  19.0                   0.0                   0.0   
660751    15715044  42.0                   4.0                   2.0   
410930    16013732  43.0                   0.0                   1.0   
405569    16535233  51.0                   0.0                   9.0   

        cheque_count_12m_g25  cheque_count_12m_g32  cheque_count_12m_g33  \
537412                   0.0                   1.0                   0.0   
607270                   1.0                   0.0                   1.0   
406983                   0.0                   0.0                   1.0   
369791                  15.0                  18.0                   6.0   
326614                   2.0                   0.0                   1.0   
...                      ...                   ...                   ...   
669733                   2.0                   0.0                   2.0   
171542                   2.0                   2.0                   0.0   
660751                   0.0                   0.0                   0.0   
410930                   1.0                   0.0                   1.0   
405569                  16.0                  14.0                   0.0   

        cheque_count_12m_g38  cheque_count_12m_g39  cheque_count_12m_g41  ...  \
537412                   0.0                   0.0                   0.0  ...   
607270                   1.0                   1.0                   1.0  ...   
406983                  10.0                   0.0                   8.0  ...   
369791                   7.0                   6.0                  26.0  ...   
326614                   1.0                   1.0                   1.0  ...   
...                      ...                   ...                   ...  ...   
669733                   0.0                   0.0                   0.0  ...   
171542                   1.0                   0.0                   1.0  ...   
660751                   0.0                   0.0                   1.0  ...   
410930                   4.0                   1.0                   1.0  ...   
405569                   6.0                   2.0                  21.0  ...   

        sale_sum_6m_g25  sale_sum_6m_g26  sale_sum_6m_g32  sale_sum_6m_g33  \
537412             0.00            63.28           380.28             0.00   
607270           192.35             0.00             0.00           752.18   
406983             0.00           934.93             0.00             0.00   
369791           153.27           134.37          2778.20           137.49   
326614           119.07             0.00             0.00           150.22   
...                 ...              ...              ...              ...   
669733           110.88            79.98             0.00           296.37   
171542            74.17             0.00            79.58             0.00   
660751             0.00             0.00             0.00             0.00   
410930             0.00           165.77             0.00            99.99   
405569           119.25          1438.70           890.45             0.00   

        sale_sum_6m_g44  sale_sum_6m_g54  stdev_days_between_visits_15d  \
537412           174.27            84.37                         0.0000   
607270             0.00           159.99                         0.0000   
406983           468.15           205.91                            NaN   
369791          2038

In [126]:
data.reset_index()

CardHolder   age  cheque_count_12m_g20  cheque_count_12m_g21  \
557927    15891401  44.0                   1.0                   5.0   
417252    16438691  52.0                   8.0                   3.0   
81470     16088345  54.0                   0.0                   1.0   
524283    16175109  29.0                   0.0                   1.0   
369200    15760394  43.0                   0.0                   0.0   
...            ...   ...                   ...                   ...   
517740    16182135  34.0                   1.0                   0.0   
11486     16006515  69.0                  11.0                   3.0   
67256     15919184  53.0                   3.0                   2.0   
269708    16128450  31.0                   0.0                   0.0   
498506    15862140  32.0                   2.0                   3.0   

        cheque_count_12m_g25  cheque_count_12m_g32  cheque_count_12m_g33  \
557927                   3.0                  19.0                  11.0   
417252                  13.0                   0.0                   5.0   
81470                    0.0                   0.0                   0.0   
524283                   3.0                   1.0                   1.0   
369200                   3.0                   0.0                   1.0   
...                      ...                   ...                   ...   
517740                   6.0                   3.0                   5.0   
11486                   13.0                   0.0                   9.0   
67256                    5.0                   2.0                   4.0   
269708                   1.0                   0.0                   1.0   
498506                   0.0                   2.0                   1.0   

        cheque_count_12m_g38  cheque_count_12m_g39  cheque_count_12m_g41  ...  \
557927                   9.0                   4.0                   4.0  ...   
417252                   2.0                   0.0                   4.0  ...   
81470                    0.0                   1.0                   0.0  ...   
524283                   1.0                   2.0                   1.0  ...   
369200                   1.0                   0.0                   0.0  ...   
...                      ...                   ...                   ...  ...   
517740                   0.0                   1.0                   3.0  ...   
11486                    3.0                   3.0                   2.0  ...   
67256                    3.0                   1.0                   7.0  ...   
269708                   1.0                   1.0                   7.0  ...   
498506                   4.0                   1.0                   1.0  ...   

        sale_sum_6m_g25  sale_sum_6m_g26  sale_sum_6m_g32  sale_sum_6m_g33  \
557927           298.33           122.73          2888.69           406.79   
417252           292.22             0.00             0.00          1154.57   
81470              0.00             0.00             0.00             0.00   
524283           227.39           459.41             0.00           326.84   
369200           410.59             0.00             0.00           153.53   
...                 ...              ...              ...              ...   
517740            95.68            99.98           224.97           875.55   
11486            796.97             0.00             0.00           401.19   
67256            562.96           726.00           259.52          1081.41   
269708            29.99            46.78             0.00           323.74   
498506             0.00           126.66           647.91            96.99   

        sale_sum_6m_g44  sale_sum_6m_g54  stdev_days_between_visits_15d  \
557927           157.96           486.80                         0.0000   
417252            98.97           566.37                         0.0000   
81470              0.00             0.00                         0.0000   
524283             0

In [125]:
data[:1000]

CardHolder   age  cheque_count_12m_g20  cheque_count_12m_g21  \
0      16095858  47.0                   3.0                  22.0   
1      15906620  57.0                   1.0                   0.0   
2      16495466  38.0                   7.0                   0.0   
3      16570217  65.0                   6.0                   3.0   
4      16346871  61.0                   0.0                   1.0   
..          ...   ...                   ...                   ...   
995    16557561  33.0                   5.0                  24.0   
996    16431589  36.0                   2.0                   0.0   
997    16179052  57.0                   2.0                   2.0   
998    16568014  22.0                   0.0                   0.0   
999    16321705  46.0                   2.0                   1.0   

     cheque_count_12m_g25  cheque_count_12m_g32  cheque_count_12m_g33  \
0                    19.0                   3.0                  28.0   
1                     2.0                   1.0                   1.0   
2                    15.0                   4.0                   9.0   
3                    25.0                   2.0                  10.0   
4                     2.0                   0.0                   2.0   
..                    ...                   ...                   ...   
995                  11.0                  20.0                  64.0   
996                   0.0                   0.0                   2.0   
997                   9.0                   1.0                   7.0   
998                   1.0                   0.0                   1.0   
999                  11.0                   3.0                   6.0   

     cheque_count_12m_g38  cheque_count_12m_g39  cheque_count_12m_g41  ...  \
0                     8.0                   7.0                   6.0  ...   
1                     1.0                   0.0                   1.0  ...   
2                     5.0                   9.0                  14.0  ...   
3                    14.0                  11.0                   8.0  ...   
4                     1.0                   0.0                   3.0  ...   
..                    ...                   ...                   ...  ...   
995                  37.0                   7.0                  88.0  ...   
996                   0.0                   0.0                   0.0  ...   
997                   2.0                   0.0                   6.0  ...   
998                   1.0                   0.0                   1.0  ...   
999                   4.0                   3.0                   5.0  ...   

     sale_sum_6m_g25  sale_sum_6m_g26  sale_sum_6m_g32  sale_sum_6m_g33  \
0             356.67           237.25           283.84          3648.23   
1              62.69            58.71            87.01           179.83   
2             533.46            83.37           593.13          1217.43   
3            1849.91           360.40           175.73           496.73   
4             168.05           461.37             0.00           237.93   
..               ...              ...              ...              ...   
995           249.85          2909.73          2404.91          9054.78   
996             0.00             0.00             0.00             0.00   
997           202.74             0.00             0.00           978.13   
998            59.00             0.00             0.00           344.56   
999           196.42             0.00             0.00             0.00   

     sale_sum_6m_g44  sale_sum_6m_g54  stdev_days_between_visits_15d  \
0            1195.37           535.42                         1.7078   
1               0.00           122.98                         0.0000   
2            1336.83          3709.82                         0.0000   
3             172.58          1246.21                         0.0000   
4             225.51           995.27                         1.4142   
..               ...         

In [130]:
data['group'].value_counts()

test       515892
control    171137
Name: group, dtype: int64

In [129]:
model = StupidModel(verbose=False)
run(data.sample(100000).reset_index(drop=True), model)

({'train': 4.766204232769795,
  'test': 1.6654030485185722,
  'train_random': 1.0532445032960092,
  'test_random': 1.123937068099588},
 {'train': [4.858175811317979,
   4.8187312098496164,
   4.231526615523393,
   5.156383294388191],
  'test': [1.0759952030089768,
   0.28193259699237916,
   3.8272728079103953,
   1.4764115861625378],
  'train_random': [1.4522405625859542,
   0.8665928863106371,
   0.5784164112516722,
   1.3157281530357727],
  'test_random': [1.1350742865096695,
   0.5629187616072159,
   1.7491938280698924,
   1.0485613962115743]})

In [109]:
import xgboost

params = {'objective': 'rank:ndcg', 'n_estimators': 100, 'eval_metric': ['ndcg', 'map']}
model = xgboost.sklearn.XGBRanker(**params)

x = data[:10000].drop(['group', 'response_att'], axis=1)
y = data[:10000]['response_att']
group = [data[:10000]['response_att'].shape[0]]

model.fit(x, y, group, verbose=True,
         eval_set=[(x, y)], eval_group=[group])

[0]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[1]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[2]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[3]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[4]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[5]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[6]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[7]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[8]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[9]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[10]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[11]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[12]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[13]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[14]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[15]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[16]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[17]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[18]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[19]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[20]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[21]	eval_0-ndcg:0.705183	eval_0-map:0.10846

XGBRanker(eval_metric=['ndcg', 'map'], objective='rank:ndcg')